server:
  port: 8080

spring:
  application:
    name: mjweb
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: My123asd!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-wait: 30000
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 3000
  thymeleaf:
    cache: false
    mode: LEGANCYHTML5


logging:
  level:
    com.zmkm: DEBUG
  file:
    path: ${user.home}/test/logs
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

async-thread-pool:
  corePoolSize: 5
  maxPoolSize: 20
  keepAliveSeconds: 30
  queueCapacity: 100
